GFQQ_Product2__c
SELECT+CMS_Lineup_ID__c,Component__c,Criteria__c,Description__c,Family__c,Fiber_Market__c,GFiber_Cost__c,GFiber_Device_Model__c,GFiber_Device_Type__c,GFiber_Min_IPv4_Subnet_Prefix__c,GFiber_Min_IPv6_Subnet_Prefix__c,Id,Line_Item_Message__c,Name,Payments_Usage_Type__c,Product_Code__c,Product_Line__c,Product_Sub_Line__c,Static_Ip_Has_Ipv4_Lan_Service__c,Static_Ip_Ipv4_Address_Count__c,Static_Ip_Ipv4_Lan_Subnet_Prefix__c++FROM+GFQQ_Product2__c

GFQQ_Error_Condition__c
SELECT+FilterType__c,FilterValue__c,Id,Index__c,Name,Operator__c,ParentRuleIsActive__c,RuleTargetsQuote__c,Rule__c,TestedField__c,TestedObject__c+FROM+GFQQ_Error_Condition__c

GFQQ_Product_Action__c
SELECT+FilterField__c,FilterValue__c,Id,Name,Operator__c,ParentRuleIsActive__c,Rule__c+FROM+GFQQ_Product_Action__c


GFQQ_Product_Feature__c
SELECT+ConfiguredSKU__c,Id,MaxOptionCount__c,MinOptionCount__c,Name,Number__c+FROM+GFQQ_Product_Feature__c

GFQQ_Product_Option__c
SELECT+Bundled__c,ConfiguredSKU__c,Feature__c,GFiber_Automatic__c,Id,MaxQuantity__c,MinQuantity__c,Name,Number__c,OptionalSKU__c,ProductCode__c,Required__c,Selected__c+FROM+GFQQ_Product_Option__c


GFQQ_Product_Rate_Plan_Charge_Tier__c
SELECT+Ending_Unit__c,Hardware_Ownership__c,Id,IsDeleted,Is_Bundled__c,LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,Name,Price_Format__c,Price__c,Product_Rate_Plan_Charge__c,Return_Window_Display_Days__c,Return_Window_Enforced_Days__c,Starting_Unit__c+FROM+GFQQ_Product_Rate_Plan_Charge_Tier__c


GFQQ_Product_Rate_Plan_Charge__c
SELECT+Apply_Discount_To__c,Charge_Model__c,Charge_Type__c,Discount_Level__c,Id,Name,Product_Rate_Plan__c,Recurrences__c,Taxable__c,Tax_Code__c,Tax_Mode__c,Trigger_Event__c,Unit_Type__c,Zuora_Product_Rate_Plan_Charge_Id__c+FROM+GFQQ_Product_Rate_Plan_Charge__c


GFQQ_Product_Rate_Plan__c
SELECT+Criteria__c,Effective_End_Date__c,Effective_Start_Date__c,Fiber_Market__c,Id,Line_Item_Message__c,Name,Product_Plan_Rate_Code__c,Product__c,Zuora_Product_Rate_Plan_Id__c+FROM+GFQQ_Product_Rate_Plan__c


GFQQ_Product_Rule__c
SELECT+Active__c,AdvancedCondition__c,ConditionsMet__c,Criteria__c,EvaluationEvent__c,External_ID__c,Fiber_Market__c,Id,Name,Product_Rule_Code__c,Scope__c,Type__c+FROM+GFQQ_Product_Rule__c

